replicaCount: 1
image:
  repository: 480294271769.dkr.ecr.us-east-2.amazonaws.com/circleciflask
  pullPolicy: IfNotPresent
  tag: "latest"
labels:
  env: "staging"
service:
  port: 5000
  targetPort: 5000
  type: LoadBalancer
replicaCount: 1
autoscaling:
  enabled: false
ingress:
  enabled: false
imagePullSecrets:
  - name: regcred
